version: "3.2"
services:
  php:
    build:
      context: .
    image: webuxmotion/flatanimals:1.0.0
    networks:
      - frontend
      - backend
    environment:
      - MYSQL_HOST=fa-mysql-app
      - MYSQL_USER=fauser
      - MYSQL_PASSWORD=fapass
      - MYSQL_DB=fa_db
    volumes:
      - ./:/var/www/html/
    ports:
      - "30001:80"
    container_name: fa-php-app
  mysql:
    image: mysql:5.7
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_USER=fauser
      - MYSQL_PASSWORD=fapass
      - MYSQL_DATABASE=fa_db
    container_name: fa-mysql-app
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    depends_on:
      - mysql
    networks:
      - backend
    ports:
      - "30002:80"
    environment:
      - PMA_HOST=fa-mysql-app
      - PMA_PORT= 3306
    volumes:
      - /sessions
    container_name: fa-phpmyadmin-app
networks:
  frontend:
  backend:
